name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "patches/v20*.patch"
      - "resources/**"
      - "scripts/**"
      - "Dockerfile"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      # Force docker to output the progress in plain
      BUILDKIT_PROGRESS: plain
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build and Extract
        shell: bash
        run: |
          make docker-extract

      - name: Generate checksum
        shell: bash
        run: |
          echo "sha256sum: $(sha256sum container_builds/bw_web_vault.tar.gz)"

      - name: "Upload web-vault artifact"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: web-vault
          compression-level: 0
          path: container_builds/bw_web_vault.tar.gz
